# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    required_providers{
        azurerm = {
            #version = "~> 1.42"
        }
    }
}
provider "azurerm" {
    features{}
    #version = "~> 1.42"
}
